package com.csri.ami.health_u.dataManagement.analyze.autoGeneratedDecisionTrees;

public class j48_walkingVsAll {

  public static double classify(Object[] i)
    throws Exception {

    double p = Double.NaN;
    p = j48_walkingVsAll.Nc1b5310(i);
    return p;
  }
  static double Nc1b5310(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() <= 1.03499915154211) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() > 1.03499915154211) {
    p = j48_walkingVsAll.N1a053081(i);
    } 
    return p;
  }
  static double N1a053081(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 0;
    } else if (((Double) i[5]).doubleValue() <= 4.86545111898875) {
    p = j48_walkingVsAll.Nab50cd2(i);
    } else if (((Double) i[5]).doubleValue() > 4.86545111898875) {
    p = j48_walkingVsAll.N15fea6062(i);
    } 
    return p;
  }
  static double Nab50cd2(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 0;
    } else if (((Double) i[7]).doubleValue() <= 0.637237580276734) {
    p = j48_walkingVsAll.N145d0683(i);
    } else if (((Double) i[7]).doubleValue() > 0.637237580276734) {
    p = j48_walkingVsAll.N16f8cd058(i);
    } 
    return p;
  }
  static double N145d0683(Object []i) {
    double p = Double.NaN;
    if (i[16] == null) {
      p = 1;
    } else if (((Double) i[16]).doubleValue() <= 0.827942719051743) {
    p = j48_walkingVsAll.N758fc94(i);
    } else if (((Double) i[16]).doubleValue() > 0.827942719051743) {
    p = j48_walkingVsAll.N4b433317(i);
    } 
    return p;
  }
  static double N758fc94(Object []i) {
    double p = Double.NaN;
    if (i[19] == null) {
      p = 1;
    } else if (((Double) i[19]).doubleValue() <= 0.233927579385001) {
    p = j48_walkingVsAll.N32fb4f5(i);
    } else if (((Double) i[19]).doubleValue() > 0.233927579385001) {
      p = 1;
    } 
    return p;
  }
  static double N32fb4f5(Object []i) {
    double p = Double.NaN;
    if (i[10] == null) {
      p = 1;
    } else if (((Double) i[10]).doubleValue() <= 9.88344310268856) {
      p = 1;
    } else if (((Double) i[10]).doubleValue() > 9.88344310268856) {
    p = j48_walkingVsAll.N11137086(i);
    } 
    return p;
  }
  static double N11137086(Object []i) {
    double p = Double.NaN;
    if (i[13] == null) {
      p = 0;
    } else if (((Double) i[13]).doubleValue() <= 0.031496062992126) {
    p = j48_walkingVsAll.N133f1d77(i);
    } else if (((Double) i[13]).doubleValue() > 0.031496062992126) {
    p = j48_walkingVsAll.Ndd5b15(i);
    } 
    return p;
  }
  static double N133f1d77(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 0.375144318184919) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 0.375144318184919) {
    p = j48_walkingVsAll.N14a99728(i);
    } 
    return p;
  }
  static double N14a99728(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.231910370119581) {
    p = j48_walkingVsAll.Na013359(i);
    } else if (((Double) i[21]).doubleValue() > 0.231910370119581) {
    p = j48_walkingVsAll.N14d334310(i);
    } 
    return p;
  }
  static double Na013359(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() <= 0.872568679111881) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() > 0.872568679111881) {
      p = 0;
    } 
    return p;
  }
  static double N14d334310(Object []i) {
    double p = Double.NaN;
    if (i[4] == null) {
      p = 1;
    } else if (((Double) i[4]).doubleValue() <= 9.68270919443353) {
      p = 1;
    } else if (((Double) i[4]).doubleValue() > 9.68270919443353) {
    p = j48_walkingVsAll.N1608e0511(i);
    } 
    return p;
  }
  static double N1608e0511(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 1;
    } else if (((Double) i[7]).doubleValue() <= 0.116565087659773) {
    p = j48_walkingVsAll.Nbf32c12(i);
    } else if (((Double) i[7]).doubleValue() > 0.116565087659773) {
    p = j48_walkingVsAll.N89fbe313(i);
    } 
    return p;
  }
  static double Nbf32c12(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() <= 1.28000979981259) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() > 1.28000979981259) {
      p = 1;
    } 
    return p;
  }
  static double N89fbe313(Object []i) {
    double p = Double.NaN;
    if (i[20] == null) {
      p = 0;
    } else if (((Double) i[20]).doubleValue() <= 0.341123045062039) {
      p = 0;
    } else if (((Double) i[20]).doubleValue() > 0.341123045062039) {
    p = j48_walkingVsAll.Nf8184314(i);
    } 
    return p;
  }
  static double Nf8184314(Object []i) {
    double p = Double.NaN;
    if (i[2] == null) {
      p = 0;
    } else if (((Double) i[2]).doubleValue() <= 0.811055623567451) {
      p = 0;
    } else if (((Double) i[2]).doubleValue() > 0.811055623567451) {
      p = 1;
    } 
    return p;
  }
  static double Ndd5b15(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 0.9508496473682) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 0.9508496473682) {
    p = j48_walkingVsAll.Nc4bcdc16(i);
    } 
    return p;
  }
  static double Nc4bcdc16(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() <= 1.44086402360188) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() > 1.44086402360188) {
      p = 1;
    } 
    return p;
  }
  static double N4b433317(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 1;
    } else if (((Double) i[3]).doubleValue() <= 12.9564998672) {
    p = j48_walkingVsAll.N128e20a18(i);
    } else if (((Double) i[3]).doubleValue() > 12.9564998672) {
    p = j48_walkingVsAll.N86f24129(i);
    } 
    return p;
  }
  static double N128e20a18(Object []i) {
    double p = Double.NaN;
    if (i[16] == null) {
      p = 0;
    } else if (((Double) i[16]).doubleValue() <= 1.24338100544569) {
    p = j48_walkingVsAll.N1100d7a19(i);
    } else if (((Double) i[16]).doubleValue() > 1.24338100544569) {
    p = j48_walkingVsAll.N171732b25(i);
    } 
    return p;
  }
  static double N1100d7a19(Object []i) {
    double p = Double.NaN;
    if (i[18] == null) {
      p = 0;
    } else if (((Double) i[18]).doubleValue() <= 0.502904764200279) {
    p = j48_walkingVsAll.Ne4f97220(i);
    } else if (((Double) i[18]).doubleValue() > 0.502904764200279) {
      p = 1;
    } 
    return p;
  }
  static double Ne4f97220(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 0.425666961829952) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 0.425666961829952) {
    p = j48_walkingVsAll.Nb4d3d521(i);
    } 
    return p;
  }
  static double Nb4d3d521(Object []i) {
    double p = Double.NaN;
    if (i[19] == null) {
      p = 0;
    } else if (((Double) i[19]).doubleValue() <= 0.189438201548432) {
      p = 0;
    } else if (((Double) i[19]).doubleValue() > 0.189438201548432) {
    p = j48_walkingVsAll.N1bf52a522(i);
    } 
    return p;
  }
  static double N1bf52a522(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.630916760081556) {
    p = j48_walkingVsAll.N1cafa9e23(i);
    } else if (((Double) i[21]).doubleValue() > 0.630916760081556) {
      p = 0;
    } 
    return p;
  }
  static double N1cafa9e23(Object []i) {
    double p = Double.NaN;
    if (i[10] == null) {
      p = 0;
    } else if (((Double) i[10]).doubleValue() <= 9.99503486642381) {
    p = j48_walkingVsAll.N10b9d0424(i);
    } else if (((Double) i[10]).doubleValue() > 9.99503486642381) {
      p = 1;
    } 
    return p;
  }
  static double N10b9d0424(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= 12.716450828) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() > 12.716450828) {
      p = 1;
    } 
    return p;
  }
  static double N171732b25(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 1.76816703120061) {
    p = j48_walkingVsAll.N140453626(i);
    } else if (((Double) i[12]).doubleValue() > 1.76816703120061) {
      p = 0;
    } 
    return p;
  }
  static double N140453626(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 1;
    } else if (((Double) i[7]).doubleValue() <= 0.142320641258993) {
    p = j48_walkingVsAll.N7fdcde27(i);
    } else if (((Double) i[7]).doubleValue() > 0.142320641258993) {
    p = j48_walkingVsAll.N7d848328(i);
    } 
    return p;
  }
  static double N7fdcde27(Object []i) {
    double p = Double.NaN;
    if (i[16] == null) {
      p = 0;
    } else if (((Double) i[16]).doubleValue() <= 1.50645758366959) {
      p = 0;
    } else if (((Double) i[16]).doubleValue() > 1.50645758366959) {
      p = 1;
    } 
    return p;
  }
  static double N7d848328(Object []i) {
    double p = Double.NaN;
    if (i[8] == null) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() <= 10.337877515848) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() > 10.337877515848) {
      p = 0;
    } 
    return p;
  }
  static double N86f24129(Object []i) {
    double p = Double.NaN;
    if (i[15] == null) {
      p = 1;
    } else if (((Double) i[15]).doubleValue() <= 0.189976291851417) {
    p = j48_walkingVsAll.N18ac73830(i);
    } else if (((Double) i[15]).doubleValue() > 0.189976291851417) {
    p = j48_walkingVsAll.N5afd2934(i);
    } 
    return p;
  }
  static double N18ac73830(Object []i) {
    double p = Double.NaN;
    if (i[11] == null) {
      p = 0;
    } else if (((Double) i[11]).doubleValue() <= 2.08703999464781) {
    p = j48_walkingVsAll.N1d609631(i);
    } else if (((Double) i[11]).doubleValue() > 2.08703999464781) {
      p = 1;
    } 
    return p;
  }
  static double N1d609631(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 0.570269228315505) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 0.570269228315505) {
    p = j48_walkingVsAll.Nb02e7a32(i);
    } 
    return p;
  }
  static double Nb02e7a32(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 0;
    } else if (((Double) i[7]).doubleValue() <= 0.330242918709237) {
    p = j48_walkingVsAll.Nbb6ab633(i);
    } else if (((Double) i[7]).doubleValue() > 0.330242918709237) {
      p = 1;
    } 
    return p;
  }
  static double Nbb6ab633(Object []i) {
    double p = Double.NaN;
    if (i[2] == null) {
      p = 1;
    } else if (((Double) i[2]).doubleValue() <= 0.577285947677178) {
      p = 1;
    } else if (((Double) i[2]).doubleValue() > 0.577285947677178) {
      p = 0;
    } 
    return p;
  }
  static double N5afd2934(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.223113301135092) {
    p = j48_walkingVsAll.N1a2961b35(i);
    } else if (((Double) i[21]).doubleValue() > 0.223113301135092) {
    p = j48_walkingVsAll.N12d03f936(i);
    } 
    return p;
  }
  static double N1a2961b35(Object []i) {
    double p = Double.NaN;
    if (i[13] == null) {
      p = 0;
    } else if (((Double) i[13]).doubleValue() <= 0.0078740157480315) {
      p = 0;
    } else if (((Double) i[13]).doubleValue() > 0.0078740157480315) {
      p = 1;
    } 
    return p;
  }
  static double N12d03f936(Object []i) {
    double p = Double.NaN;
    if (i[18] == null) {
      p = 0;
    } else if (((Double) i[18]).doubleValue() <= 0.843546713025527) {
    p = j48_walkingVsAll.N5ffb1837(i);
    } else if (((Double) i[18]).doubleValue() > 0.843546713025527) {
    p = j48_walkingVsAll.Na401c257(i);
    } 
    return p;
  }
  static double N5ffb1837(Object []i) {
    double p = Double.NaN;
    if (i[11] == null) {
      p = 0;
    } else if (((Double) i[11]).doubleValue() <= 4.70632073353323) {
    p = j48_walkingVsAll.N15dfd7738(i);
    } else if (((Double) i[11]).doubleValue() > 4.70632073353323) {
    p = j48_walkingVsAll.N55571e51(i);
    } 
    return p;
  }
  static double N15dfd7738(Object []i) {
    double p = Double.NaN;
    if (i[19] == null) {
      p = 0;
    } else if (((Double) i[19]).doubleValue() <= 0.409096233774988) {
    p = j48_walkingVsAll.N1abc7b939(i);
    } else if (((Double) i[19]).doubleValue() > 0.409096233774988) {
    p = j48_walkingVsAll.Nb09e8948(i);
    } 
    return p;
  }
  static double N1abc7b939(Object []i) {
    double p = Double.NaN;
    if (i[13] == null) {
      p = 0;
    } else if (((Double) i[13]).doubleValue() <= 0.0236220472440945) {
    p = j48_walkingVsAll.Nc55e3640(i);
    } else if (((Double) i[13]).doubleValue() > 0.0236220472440945) {
    p = j48_walkingVsAll.N5e060245(i);
    } 
    return p;
  }
  static double Nc55e3640(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 0;
    } else if (((Double) i[12]).doubleValue() <= 2.75118222642196) {
    p = j48_walkingVsAll.N1ac3c0841(i);
    } else if (((Double) i[12]).doubleValue() > 2.75118222642196) {
    p = j48_walkingVsAll.N1f630dc43(i);
    } 
    return p;
  }
  static double N1ac3c0841(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= 18.57404545095) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() > 18.57404545095) {
    p = j48_walkingVsAll.N9971ad42(i);
    } 
    return p;
  }
  static double N9971ad42(Object []i) {
    double p = Double.NaN;
    if (i[16] == null) {
      p = 0;
    } else if (((Double) i[16]).doubleValue() <= 1.8748796058413) {
      p = 0;
    } else if (((Double) i[16]).doubleValue() > 1.8748796058413) {
      p = 1;
    } 
    return p;
  }
  static double N1f630dc43(Object []i) {
    double p = Double.NaN;
    if (i[4] == null) {
      p = 0;
    } else if (((Double) i[4]).doubleValue() <= 9.28339532240268) {
    p = j48_walkingVsAll.N1c5c144(i);
    } else if (((Double) i[4]).doubleValue() > 9.28339532240268) {
      p = 0;
    } 
    return p;
  }
  static double N1c5c144(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 3.94413155539424) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 3.94413155539424) {
      p = 0;
    } 
    return p;
  }
  static double N5e060245(Object []i) {
    double p = Double.NaN;
    if (i[17] == null) {
      p = 0;
    } else if (((Double) i[17]).doubleValue() <= 0.984802487550629) {
    p = j48_walkingVsAll.Ndc840f46(i);
    } else if (((Double) i[17]).doubleValue() > 0.984802487550629) {
      p = 0;
    } 
    return p;
  }
  static double Ndc840f46(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.773853654276269) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() > 0.773853654276269) {
    p = j48_walkingVsAll.N1621e4247(i);
    } 
    return p;
  }
  static double N1621e4247(Object []i) {
    double p = Double.NaN;
    if (i[11] == null) {
      p = 0;
    } else if (((Double) i[11]).doubleValue() <= 2.48740020301104) {
      p = 0;
    } else if (((Double) i[11]).doubleValue() > 2.48740020301104) {
      p = 1;
    } 
    return p;
  }
  static double Nb09e8948(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 2.27332674239355) {
    p = j48_walkingVsAll.N178703849(i);
    } else if (((Double) i[12]).doubleValue() > 2.27332674239355) {
    p = j48_walkingVsAll.Nfa9cf50(i);
    } 
    return p;
  }
  static double N178703849(Object []i) {
    double p = Double.NaN;
    if (i[22] == null) {
      p = 0;
    } else if (((Double) i[22]).doubleValue() <= -0.0522353392577183) {
      p = 0;
    } else if (((Double) i[22]).doubleValue() > -0.0522353392577183) {
      p = 1;
    } 
    return p;
  }
  static double Nfa9cf50(Object []i) {
    double p = Double.NaN;
    if (i[17] == null) {
      p = 1;
    } else if (((Double) i[17]).doubleValue() <= 0.986879221184953) {
      p = 1;
    } else if (((Double) i[17]).doubleValue() > 0.986879221184953) {
      p = 0;
    } 
    return p;
  }
  static double N55571e51(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 2.15416227812576) {
    p = j48_walkingVsAll.Nca832752(i);
    } else if (((Double) i[12]).doubleValue() > 2.15416227812576) {
    p = j48_walkingVsAll.N16897b253(i);
    } 
    return p;
  }
  static double Nca832752(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.724760928218192) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() > 0.724760928218192) {
      p = 0;
    } 
    return p;
  }
  static double N16897b253(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= 18.0104876422) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() > 18.0104876422) {
    p = j48_walkingVsAll.N1bf677054(i);
    } 
    return p;
  }
  static double N1bf677054(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 3.16725910593567) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 3.16725910593567) {
    p = j48_walkingVsAll.N1201a2555(i);
    } 
    return p;
  }
  static double N1201a2555(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() <= 2.27299438519486) {
    p = j48_walkingVsAll.N94948a56(i);
    } else if (((Double) i[1]).doubleValue() > 2.27299438519486) {
      p = 0;
    } 
    return p;
  }
  static double N94948a56(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() <= 2.0038465130356) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() > 2.0038465130356) {
      p = 1;
    } 
    return p;
  }
  static double Na401c257(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() <= 2.42097874668807) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() > 2.42097874668807) {
      p = 0;
    } 
    return p;
  }
  static double N16f8cd058(Object []i) {
    double p = Double.NaN;
    if (i[16] == null) {
      p = 1;
    } else if (((Double) i[16]).doubleValue() <= 2.22522211899402) {
      p = 1;
    } else if (((Double) i[16]).doubleValue() > 2.22522211899402) {
    p = j48_walkingVsAll.N85af8059(i);
    } 
    return p;
  }
  static double N85af8059(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 1.78509110612584) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() > 1.78509110612584) {
    p = j48_walkingVsAll.Nc5135560(i);
    } 
    return p;
  }
  static double Nc5135560(Object []i) {
    double p = Double.NaN;
    if (i[14] == null) {
      p = 0;
    } else if (((Double) i[14]).doubleValue() <= 125.561837995856) {
    p = j48_walkingVsAll.N78717161(i);
    } else if (((Double) i[14]).doubleValue() > 125.561837995856) {
      p = 1;
    } 
    return p;
  }
  static double N78717161(Object []i) {
    double p = Double.NaN;
    if (i[8] == null) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() <= 8.37814643021453) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() > 8.37814643021453) {
      p = 0;
    } 
    return p;
  }
  static double N15fea6062(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() <= 6.82579599208302) {
    p = j48_walkingVsAll.N1457cb63(i);
    } else if (((Double) i[5]).doubleValue() > 6.82579599208302) {
      p = 1;
    } 
    return p;
  }
  static double N1457cb63(Object []i) {
    double p = Double.NaN;
    if (i[21] == null) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() <= 0.525579993254284) {
      p = 1;
    } else if (((Double) i[21]).doubleValue() > 0.525579993254284) {
    p = j48_walkingVsAll.N18fef3d64(i);
    } 
    return p;
  }
  static double N18fef3d64(Object []i) {
    double p = Double.NaN;
    if (i[12] == null) {
      p = 1;
    } else if (((Double) i[12]).doubleValue() <= 9.38862498070359) {
    p = j48_walkingVsAll.Na3bcc165(i);
    } else if (((Double) i[12]).doubleValue() > 9.38862498070359) {
      p = 1;
    } 
    return p;
  }
  static double Na3bcc165(Object []i) {
    double p = Double.NaN;
    if (i[11] == null) {
      p = 1;
    } else if (((Double) i[11]).doubleValue() <= 4.90108315608017) {
      p = 1;
    } else if (((Double) i[11]).doubleValue() > 4.90108315608017) {
    p = j48_walkingVsAll.N1bd472266(i);
    } 
    return p;
  }
  static double N1bd472266(Object []i) {
    double p = Double.NaN;
    if (i[10] == null) {
      p = 0;
    } else if (((Double) i[10]).doubleValue() <= 11.0818974845772) {
    p = j48_walkingVsAll.N1891d8f67(i);
    } else if (((Double) i[10]).doubleValue() > 11.0818974845772) {
    p = j48_walkingVsAll.N1a73d3c70(i);
    } 
    return p;
  }
  static double N1891d8f67(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() <= 2.32773190029681) {
      p = 1;
    } else if (((Double) i[1]).doubleValue() > 2.32773190029681) {
    p = j48_walkingVsAll.Nf3d6a568(i);
    } 
    return p;
  }
  static double Nf3d6a568(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() <= 5.64457051145734) {
    p = j48_walkingVsAll.N911f7169(i);
    } else if (((Double) i[5]).doubleValue() > 5.64457051145734) {
      p = 0;
    } 
    return p;
  }
  static double N911f7169(Object []i) {
    double p = Double.NaN;
    if (i[20] == null) {
      p = 1;
    } else if (((Double) i[20]).doubleValue() <= -0.242425046450592) {
      p = 1;
    } else if (((Double) i[20]).doubleValue() > -0.242425046450592) {
      p = 0;
    } 
    return p;
  }
  static double N1a73d3c70(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() <= 6.68270065941048) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() > 6.68270065941048) {
      p = 0;
    } 
    return p;
  }
}
