package com.csri.ami.health_u.dataManagement.analyze.autoGeneratedDecisionTrees;

class sound_j48_1 {

  public static double classify(Object [] i)
    throws Exception {

    double p = Double.NaN;
    p = sound_j48_1.N134ce4a0(i);
    return p;
  }
  static double N134ce4a0(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() <= -0.286691786259773) {
      p = 1;
    } else if (((Double) i[5]).doubleValue() > -0.286691786259773) {
    p = sound_j48_1.N136a1a11(i);
    } 
    return p;
  }
  static double N136a1a11(Object []i) {
    double p = Double.NaN;
    if (i[2] == null) {
      p = 0;
    } else if (((Double) i[2]).doubleValue() <= 0.689512425250335) {
    p = sound_j48_1.N1ad6b4b2(i);
    } else if (((Double) i[2]).doubleValue() > 0.689512425250335) {
    p = sound_j48_1.N1bb9a5824(i);
    } 
    return p;
  }
  static double N1ad6b4b2(Object []i) {
    double p = Double.NaN;
    if (i[4] == null) {
      p = 0;
    } else if (((Double) i[4]).doubleValue() <= 0.0302994817904985) {
    p = sound_j48_1.N5f2db03(i);
    } else if (((Double) i[4]).doubleValue() > 0.0302994817904985) {
    p = sound_j48_1.Nbe49e021(i);
    } 
    return p;
  }
  static double N5f2db03(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 0;
    } else if (((Double) i[5]).doubleValue() <= 0.321597405213317) {
    p = sound_j48_1.Nb0a3f54(i);
    } else if (((Double) i[5]).doubleValue() > 0.321597405213317) {
      p = 0;
    } 
    return p;
  }
  static double Nb0a3f54(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= 0.291080065005928) {
    p = sound_j48_1.Ndc41c55(i);
    } else if (((Double) i[3]).doubleValue() > 0.291080065005928) {
    p = sound_j48_1.N1236cd520(i);
    } 
    return p;
  }
  static double Ndc41c55(Object []i) {
    double p = Double.NaN;
    if (i[5] == null) {
      p = 0;
    } else if (((Double) i[5]).doubleValue() <= 0.280135924899308) {
      p = 0;
    } else if (((Double) i[5]).doubleValue() > 0.280135924899308) {
    p = sound_j48_1.N6214f56(i);
    } 
    return p;
  }
  static double N6214f56(Object []i) {
    double p = Double.NaN;
    if (i[9] == null) {
      p = 0;
    } else if (((Double) i[9]).doubleValue() <= 0.5807732356132691) {
    p = sound_j48_1.N14e113b7(i);
    } else if (((Double) i[9]).doubleValue() > 0.5807732356132691) {
      p = 0;
    } 
    return p;
  }
  static double N14e113b7(Object []i) {
    double p = Double.NaN;
    if (i[0] == null) {
      p = 0;
    } else if (((Double) i[0]).doubleValue() <= -0.45280673103976754) {
      p = 0;
    } else if (((Double) i[0]).doubleValue() > -0.45280673103976754) {
    p = sound_j48_1.N4d76b48(i);
    } 
    return p;
  }
  static double N4d76b48(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 0;
    } else if (((Double) i[7]).doubleValue() <= 0.697544218253799) {
    p = sound_j48_1.N1ac5f139(i);
    } else if (((Double) i[7]).doubleValue() > 0.697544218253799) {
      p = 0;
    } 
    return p;
  }
  static double N1ac5f139(Object []i) {
    double p = Double.NaN;
    if (i[4] == null) {
      p = 0;
    } else if (((Double) i[4]).doubleValue() <= -1.129026339697775) {
      p = 0;
    } else if (((Double) i[4]).doubleValue() > -1.129026339697775) {
    p = sound_j48_1.N195dd5b10(i);
    } 
    return p;
  }
  static double N195dd5b10(Object []i) {
    double p = Double.NaN;
    if (i[1] == null) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() <= -0.804269295366029) {
      p = 0;
    } else if (((Double) i[1]).doubleValue() > -0.804269295366029) {
    p = sound_j48_1.N1f78b6811(i);
    } 
    return p;
  }
  static double N1f78b6811(Object []i) {
    double p = Double.NaN;
    if (i[6] == null) {
      p = 0;
    } else if (((Double) i[6]).doubleValue() <= -0.455315599825004) {
      p = 0;
    } else if (((Double) i[6]).doubleValue() > -0.455315599825004) {
    p = sound_j48_1.Ne183e912(i);
    } 
    return p;
  }
  static double Ne183e912(Object []i) {
    double p = Double.NaN;
    if (i[8] == null) {
      p = 0;
    } else if (((Double) i[8]).doubleValue() <= 0.6246921240014085) {
    p = sound_j48_1.N19b46dc13(i);
    } else if (((Double) i[8]).doubleValue() > 0.6246921240014085) {
      p = 0;
    } 
    return p;
  }
  static double N19b46dc13(Object []i) {
    double p = Double.NaN;
    if (i[2] == null) {
      p = 0;
    } else if (((Double) i[2]).doubleValue() <= -0.6457702575953035) {
      p = 0;
    } else if (((Double) i[2]).doubleValue() > -0.6457702575953035) {
    p = sound_j48_1.N149310214(i);
    } 
    return p;
  }
  static double N149310214(Object []i) {
    double p = Double.NaN;
    if (i[10] == null) {
      p = 0;
    } else if (((Double) i[10]).doubleValue() <= 0.558583370703433) {
    p = sound_j48_1.N30ae4115(i);
    } else if (((Double) i[10]).doubleValue() > 0.558583370703433) {
      p = 0;
    } 
    return p;
  }
  static double N30ae4115(Object []i) {
    double p = Double.NaN;
    if (i[6] == null) {
      p = 0;
    } else if (((Double) i[6]).doubleValue() <= 0.5335940264054211) {
    p = sound_j48_1.N420416(i);
    } else if (((Double) i[6]).doubleValue() > 0.5335940264054211) {
      p = 0;
    } 
    return p;
  }
  static double N420416(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= -0.05738396220826385) {
    p = sound_j48_1.Nee1ede17(i);
    } else if (((Double) i[3]).doubleValue() > -0.05738396220826385) {
      p = 0;
    } 
    return p;
  }
  static double Nee1ede17(Object []i) {
    double p = Double.NaN;
    if (i[4] == null) {
      p = 0;
    } else if (((Double) i[4]).doubleValue() <= -0.227054033444748) {
    p = sound_j48_1.N12c8fa818(i);
    } else if (((Double) i[4]).doubleValue() > -0.227054033444748) {
      p = 0;
    } 
    return p;
  }
  static double N12c8fa818(Object []i) {
    double p = Double.NaN;
    if (i[0] == null) {
      p = 0;
    } else if (((Double) i[0]).doubleValue() <= 0.104654812445675) {
    p = sound_j48_1.N8b8a4719(i);
    } else if (((Double) i[0]).doubleValue() > 0.104654812445675) {
      p = 0;
    } 
    return p;
  }
  static double N8b8a4719(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= -1.323139542869985) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() > -1.323139542869985) {
      p = 0;
    } 
    return p;
  }
  static double N1236cd520(Object []i) {
    double p = Double.NaN;
    if (i[9] == null) {
      p = 0;
    } else if (((Double) i[9]).doubleValue() <= 0.209930605506026) {
      p = 0;
    } else if (((Double) i[9]).doubleValue() > 0.209930605506026) {
      p = 0;
    } 
    return p;
  }
  static double Nbe49e021(Object []i) {
    double p = Double.NaN;
    if (i[10] == null) {
      p = 2;
    } else if (((Double) i[10]).doubleValue() <= -0.847247553395858) {
      p = 2;
    } else if (((Double) i[10]).doubleValue() > -0.847247553395858) {
    p = sound_j48_1.Ne41bc322(i);
    } 
    return p;
  }
  static double Ne41bc322(Object []i) {
    double p = Double.NaN;
    if (i[9] == null) {
      p = 2;
    } else if (((Double) i[9]).doubleValue() <= -0.496918963926216) {
      p = 2;
    } else if (((Double) i[9]).doubleValue() > -0.496918963926216) {
    p = sound_j48_1.N1dacccc23(i);
    } 
    return p;
  }
  static double N1dacccc23(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() <= 0.291080065005928) {
      p = 0;
    } else if (((Double) i[3]).doubleValue() > 0.291080065005928) {
      p = 1;
    } 
    return p;
  }
  static double N1bb9a5824(Object []i) {
    double p = Double.NaN;
    if (i[7] == null) {
      p = 1;
    } else if (((Double) i[7]).doubleValue() <= 0.192823366308333) {
    p = sound_j48_1.N1922f4625(i);
    } else if (((Double) i[7]).doubleValue() > 0.192823366308333) {
    p = sound_j48_1.N15d338827(i);
    } 
    return p;
  }
  static double N1922f4625(Object []i) {
    double p = Double.NaN;
    if (i[8] == null) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() <= -0.300530019129295) {
      p = 1;
    } else if (((Double) i[8]).doubleValue() > -0.300530019129295) {
    p = sound_j48_1.N5dc99426(i);
    } 
    return p;
  }
  static double N5dc99426(Object []i) {
    double p = Double.NaN;
    if (i[3] == null) {
      p = 2;
    } else if (((Double) i[3]).doubleValue() <= -0.937763529910154) {
      p = 2;
    } else if (((Double) i[3]).doubleValue() > -0.937763529910154) {
      p = 1;
    } 
    return p;
  }
  static double N15d338827(Object []i) {
    double p = Double.NaN;
    if (i[0] == null) {
      p = 2;
    } else if (((Double) i[0]).doubleValue() <= -0.716447400054683) {
    p = sound_j48_1.N1e2670b28(i);
    } else if (((Double) i[0]).doubleValue() > -0.716447400054683) {
      p = 1;
    } 
    return p;
  }
  static double N1e2670b28(Object []i) {
    double p = Double.NaN;
    if (i[8] == null) {
      p = 0;
    } else if (((Double) i[8]).doubleValue() <= 0.3839208753994305) {
      p = 0;
    } else if (((Double) i[8]).doubleValue() > 0.3839208753994305) {
      p = 0;
    } 
    return p;
  }
}
